name: Secret Scan
description: Custom GitHub Action to Scan Secret Alerts
inputs:
  repo_owner:
    required: true
    description: GitHub Repository Owner
  repo_name:
    required: true
    description: GitHub Repository Name
  pat_token:
    description: GitHub Token
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check secret scanning alerts
      env:
        GH_TOKEN: ${{ inputs.pat_token }}
      shell: bash
      run: |
        echo "Checking secret scanning alerts..."

        gh api -X get "repos/${{ inputs.repo_owner }}/${{ inputs.repo_name }}/secret-scanning/alerts" --paginate -H "Accept: application/vnd.github+json" -F state=open --jq '.' > secret_alerts.json

        count=$(jq length secret_alerts.json)
        echo "Found $count open secret scanning alerts"
        if [ "$count" -gt 0 ]; then
          echo "❌ Failing due to secret leaks"
          exit 1